version: '3'

services:
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
    api:
        # restart: always
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mongo
        image: blackparadise0407/hotel_manage_server
        env_file:
            - .prod.env
        environment:
            - NODE_ENV=production
        ports:
            - '8008:8008'
volumes:
    mongodb:
